### ISSUE TITLE
[Suggestion] Output commands are like messages

### ISSUE THREAD

**Issue by luoxingzlx** [McJtyMods/FxControl#11]
Can you add the function of output command? Because there will be more operability, such as implementing such code.I didn't see this feature on the wiki, Is it hard to implement?

> 

    {
        "helditem": "minecraft:stick",
        "block": "minecraft:chest",
        "result": "allow"
    },
    {
        "block": "minecraft:chest",
        "command": "/gamestage add @p copper",
        "explosion": "10,true,true",
        "result": "deny"
    }

**Comment by McJty** [comment]
Implemented for next release

**Comment by McJty** [comment]
Although for gamestages you will also be able to use the new 'addstage' command that I'm going to add to next version as well. Should be more efficient

**Comment by luoxingzlx** [comment]
Thank you for your advice. I'll try to use it.
