### ISSUE TITLE
mintime and maxtime only work for first 23000 ticks

### ISSUE THREAD

**Issue by TheQKnight** [McJtyMods/FxControl#14]
after the first 23000 ticks, these conditions don't work anymore.

Heres my script

  {
    "timeout": 20,
    "dimension": 0,
	"minheight": 110,
	"mintime": 13000,
	"maxtime": 23000,
    "potion": [ "thaumcraft:blurredvision,100,0", "minecraft:hunger,100,0" ]
  },

so after the first day this stops working

**Comment by McJty** [comment]
Will be fixed next release
