### ISSUE TITLE
Y-Axis Place Events Ignore Mod function

### ISSUE THREAD

**Issue by Boolyman** [McJtyMods/FxControl#18]
Im trying to prevent players from building bases at certain ylevels... I figured your mod would help me accomplish this, but it is not working.  When I use the below script, I can't place ANYTHING below Y25, from any mod.  When I try to add a global "allow" command before the one below... it ignores the one below.  I also tried it with  minecraft:furnace, and the results are the same.

 {
   "maxheight": 25,
   "mod": "enderio",
   "message": "Pressure at this depth will not allow this block to stick.",
   "result": "deny"
 },

**Comment by Boolyman** [comment]
Can I recommend an example of a Place Event script on your wiki... it seems like every other function has an example, except that.

**Comment by McJty** [comment]
The problem is that at this moment the 'mod' attribute is not supported for place events. I'll see what I can do

**Comment by McJty** [comment]
Fixed for next release

**Comment by Boolyman** [comment]
This is still broken.
