### ISSUE TITLE
'Setblock' action not working in combination with 'breakevent'

### ISSUE THREAD

**Issue by imIrony** [McJtyMods/FxControl#2]
Using the 'setblock' action in combination with the 'breakevent' results in the 'breakevent' passing but the 'setblock' portion not occurring.

This is the example I used to test that the message did pass through but the block was never replaced to the new block type.

{
   "block": "minecraft:log",
   "message": "Log detected!",
   "setblock": {"block": "minecraft:wool"}
}

However using the same example works in combination with the 'rightclick' event instead.

**Comment by McJty** [comment]
The problem is that you need to add "result": "deny". Because you let the break go through which means Minecraft itself will replace the block with air AFTER the wool has been put there
