### ISSUE TITLE
Caught exception from FxControl Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by 3jlowes** [McJtyMods/FxControl#3]
crash report: https://pastebin.com/CDb0caPL
breakevents.json: https://pastebin.com/uJ9YB9Gg

In an environment with just fx control the game crashes. the only modified file is breakevents. If there is something wrong with my breakevents JSON then I sincerely apologize.

Thanks :D

**Comment by McJty** [comment]
There is indeed something wrong with your breakevents but that shouldn't cause a crash. I'll make sure you get a proper error instead. The error in json is this line:

        "result:" "deny"                                              

The semicolon is at the wrong spot

**Comment by McJty** [comment]
Actually in addition to the problem in your pastebin there is actually a real bug. Even after correcting it will not work. I will fix this

**Comment by McJty** [comment]
As a workaround for this bug you can add a dummy: "item": "minecraft:stick" or something to the json. That will still do the right thing but it will not crash

**Comment by McJty** [comment]
Fixed next release

**Comment by 3jlowes** [comment]
Hm I must have misclicked or something whilst uploading to pastebin. I did not mean for the semicolon to be there. Thanks for the quick reply :D my original file had the semicolon in the right spot.
