### ISSUE TITLE
Bugs with FxControl: phases & potion effects

### ISSUE THREAD

**Issue by Drip2Hardd** [McJtyMods/FxControl#40]
Modlist: fxcontrol & incontrol
Mod: Fxcontrol
Version: 3.0.10 1.18.2
Not sure if just a noob but noticed the following bugs with “effects.json” using below code
Only first effect in list is applied, i.e. in below wither is applied only, no poison (poison is only applied if we switch wither with poison)
BUG 1 example
[
    {
        "timeout": 20,
        "potion": "minecraft:wither,30,1"
    },
    {
        "timeout": 20,
        "potion": "minecraft:poison,30,1"
    }
]

Phase conditions like “winter” & “mindaycout” don’t work
•    With winter (pretty sure applied to summer and other seasons), player will just never receive effect regardless of season
•    With “mindaycount”, it is just ignored i.e. player is given effect the second they spawn in
•    However found “mintime” does work
BUG 2 example
[
    {
        "summer": true,
        "timeout": 20,
        "potion": "minecraft:wither,30,1"
    }
]
OR
[
    {
        "mindaycount": 2,
        "timeout": 20,
        "potion": "minecraft:wither,30,1"
    }
]

**Comment by McJty** [comment]
This is normal. As with all rule files (except for loot.json) only the first matching rule is executed
