### ISSUE TITLE
Trying to remove an item from the hand while right clicking

### ISSUE THREAD

**Issue by Zergmazter** [McJtyMods/FxControl#5]
I'm trying to have an item removed from my selected hand when I right click:

[
    {
    "helditem":  "minecraft:stone", 
    "remove":  "minecraft:stone"
    }
]

This is not working. I have tried combinations upon combinations of this script but none do what I wanted it to do. I don't know if this is just not implemented. Why? I wanted to consume an item when right clicking so that I can place a block of my choice with the "setblock" option.

I already know how to use the "setblock", but I can't remove an item from my hand.

**Comment by McJty** [comment]
This is not yet possible I'm afraid. I'll see about implementing this

**Comment by McJty** [comment]
Next release of Fx Control will have a solution for this
