### ISSUE TITLE
The "sethelditem" sometimes causes item to disappear in the "RightClick" Json

### ISSUE THREAD

**Issue by Zergmazter** [McJtyMods/FxControl#9]
My code is:

```
[
    {
    "helditem": "contenttweaker:iron_rod",
    "sethelditem": {"item": "contenttweaker:hot_iron_rod"}
    }
]
```

I noticed if I right click with a single item it will be replaced as it should, but when I have more than 1 item (example: x64) it will also replace it as it should, and then the system breaks. From that point forward the items will just disappear when right clicking, and no replacing will be done.

EDIT:

I Just found out another bug. Seems to be related to the first bug I posted here. Let me explain:

Here is my action bar [][][][][][][][][]. If I put 1 "iron_rod" on each box, right click and turn each into a "hot_iron_rod", it works. 

Now the bug:

Left clicking twice on any of the "hot_iron_rod" to consolidate them into a stack of x9, yields instead x1 "hot_iron_rod". The other ones just disappear as if they are ghost items.

**Comment by McJty** [comment]
In the version I just released I think I fixed this problem

**Comment by Zergmazter** [comment]
This issue was partially fixed with the latest release. It could work as it stands until the script gets a bit more complicated. Here a more elaborate example of how and where it breaks in the same way it was breaking before:

```
[
    {
    "helditem": "contenttweaker:iron_rod",
    "sethelditem": {"item": "contenttweaker:hot_iron_rod"}
    },
    {
    "helditem": "contenttweaker:hot_iron_rod",
    "sethelditem": {"item": "contenttweaker:iron_rod"}
    }
]
```

Pretty much I tried reverting my new item to the old one, but the issue that was fixed returned. This only happens however if it involves the same item. Having multiple items in the script such as tin, copper, bronze, gold, iron and steel rods all work as intended as long as you are not trying to revert back to an entry already entered in the scrip such as the script I provided above.

It is already usable as it is, so I'm not complaining. It would be cool however if it could be done as in the script I provided above.

**Comment by McJty** [comment]
Can you also reproduce this with vanilla items? Because I can't see what's wrong now

**Comment by Zergmazter** [comment]
```
 [
     {
     "helditem": "minecraft:coal",
     "sethelditem": {"item": "minecraft:diamond"}
     }
 ]
```

This part works as intended. When I add the next 2 lines of code it now stops from working at all with vanilla items:

```
 [
     {
     "helditem": "minecraft:coal",
     "sethelditem": {"item": "minecraft:diamond"}
     },
     {
     "helditem": "minecraft:diamond",
     "sethelditem": {"item": "minecraft:coal"}
     }
 ]
```

**Comment by McJty** [comment]
Ah actually that's probably to be expected. If you put the rules like that in the file then they will fire in order. So first you will replace coal with diamond and then the second rule fires which will replace diamond with coal again. So apparently nothing happens.

**Comment by Zergmazter** [comment]
Oh so apparently "nothing" happens, but its just happening so fast we can't see it. I see. I was expecting the wrong thing. I thought I could just trigger it back to the original item on right click again.
